{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d00ad9df-67b6-48da-bbaa-dea69d9b7123",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "from sklearn.base import BaseEstimator, ClassifierMixin\n",
    "\n",
    "from LSSVMClassifier2 import LSSVMClassification\n",
    "\n",
    "\"\"\"\n",
    "Least Squares Support Vector Machine (LS-SVM)\n",
    "Multi-class Classification\n",
    "\n",
    "This implementation uses a One-vs-Rest (OvR) strategy.\n",
    "For each class, a binary LS-SVM classifier is trained\n",
    "against all remaining classes.\n",
    "\"\"\"\n",
    "\n",
    "class LSSVMMultiClass(BaseEstimator, ClassifierMixin):\n",
    "    \"\"\"\n",
    "    Multi-class Least Squares Support Vector Machine classifier.\n",
    "\n",
    "    This implementation extends the binary LS-SVM classifier\n",
    "    using a One-vs-Rest (OvR) strategy.\n",
    "    \"\"\"\n",
    "    def __init__(self, gamma=1, kernel='rbf', sigma=1):\n",
    "          \"\"\"\n",
    "    Initialize the multi-class LS-SVM classifier.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    X : ndarray\n",
    "        Training feature matrix.\n",
    "\n",
    "    y : ndarray\n",
    "        Target labels.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    self\n",
    "        Fitted classifier.\n",
    "    \"\"\"\n",
    "    def fit(self, X, y):\n",
    "        \n",
    "         for label in labels: \n",
    "             \n",
    "            y_binary = np.where(y == label, 1, -1)\n",
    "            \n",
    "            model = LSSVMClassification(\n",
    "                gamma = self.gamma,\n",
    "                kernel = self.kernel,\n",
    "                sigma = self.sigma\n",
    "            )\n",
    "            \n",
    "            model.fit(X, y_binary)\n",
    "            self.models[label] = model\n",
    "             \n",
    "        return self \n",
    "        \n",
    "        # To train one binary classifier for each class\n",
    "        for label in labels: \n",
    "            y_binary = np.where(y == label, 1, -1)\n",
    "\n",
    "            print(label)\n",
    "            print(np.unique(y_binary))\n",
    "\n",
    "\n",
    "    def predict(self, X: np.ndarray) -> np.ndarray: \n",
    "        \"\"\"\n",
    "    Predict the class labels for a set of feature vectors.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    X : ndarray\n",
    "        Feature vectors to classify.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    ndarray\n",
    "        Predicted class labels.\n",
    "    \"\"\"\n",
    "        # Save all decision values of binary classifiers\n",
    "        scores = []\n",
    "        \n",
    "        # Going through the labels in a vast order \n",
    "        labels = sorted(self.models.keys())\n",
    "        \n",
    "        for label in labels:\n",
    "            \n",
    "            model = self.models[label]\n",
    "            \n",
    "            # Decision values of this specific classifier\n",
    "            decision= model.decision_function(X)\n",
    "\n",
    "            scores.append(decision) \n",
    "        # Matrix: row = data sample, column = classifier\n",
    "        scores = np.column_stack(scores)\n",
    "        \n",
    "        # Picks classifier with highest decision value PER DATA SAMPLE\n",
    "        best = np.argmax(scores, axis=1)\n",
    "\n",
    "        predicitions = np.array(labels)[best] #original class labels \n",
    "\n",
    "        return predictions "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
